#!/usr/bin/env bash
# PreToolUse hook: block edits to protected files
# Tailored for Forge — only the rules that apply at day 1 (no bun.lockb, no husky yet)
# Adapted from gigaverse-app/gigaverse-web-app/.claude/hooks/protect-files.sh
# Exit 2 = block, Exit 0 = allow

file="$TOOL_INPUT_file_path"

[ -z "$file" ] && exit 0

# Normalize: strip the project dir prefix for pattern matching
rel="${file#$CLAUDE_PROJECT_DIR/}"

# 1. Environment files (secrets)
case "$rel" in
  .env|.env.*|.dev.vars|apps/*/.env|apps/*/.env.*)
    echo "BLOCKED: $rel is an environment file containing secrets." >&2
    exit 2
    ;;
esac

# 2. Git internals
case "$rel" in
  .git/*)
    echo "BLOCKED: $rel is inside .git/." >&2
    exit 2
    ;;
esac

# 3. Auto-generated files (TanStack Router route trees, future codegen)
case "$rel" in
  *.gen.ts|*.gen.tsx)
    echo "BLOCKED: $rel is auto-generated by tooling. Do not edit manually." >&2
    exit 2
    ;;
esac

exit 0
